### ISSUE TITLE
Rust at Cummins

### ISSUE THREAD

**Issue by risbansal** [rusthacks/OpenDesign#1] opened 2018-03-07 08:07 UTC
## Goal: 
Poster for Event

## Info: 
It will be used for Publicity of Event Online.

## Style Information: 
Agenda: Rust + VR + AR
Venue: Mechanical Auditorium, Cummins College, Pune
Date: 17th March
Time: 10AM-5:00PM
Hands-on Workshop.

## Deadline: 
10th March

## Tag: 
Design Needed

**Comment by nomadicmehul** [comment] 2018-03-07 08:10
Since this event has more Women participants so its good if we can reflect that as well in the poster as a theme.  Just a suggestion. Rest, over to @pransh15

**Comment by pransh15** [comment] 2018-03-07 08:47
I have a few questions for @risbansal :

1. Do you have a broader event name or is it just supposed to be "Hands-On Workshop Rust+VR+AR"?
2. Please share your college's logo if that's supposed to be used.
3. Do you need a single image for all of Social Media?

**Comment by risbansal** [comment] 2018-03-07 09:20
The Event Name is Rust at  Cummins. Majorly it is a  Rust event. VR and AR are addons. We can mention Title Rust at Cummins and Mention AR and VR. But your suggestions are also welcome. 

link to college logo
https://duckduckgo.com/?q=cummins+college+logo&t=fpas&iax=images&ia=images&iai=http%3A%2F%2Fwww.spaark.co.in%2Fimages%2FCummins_college.png

Yes one image will be good.

**Comment by pransh15** [comment] 2018-03-07 12:03
![rustatcummins](https://user-images.githubusercontent.com/18158596/37091278-9132a2c4-222d-11e8-96fa-9752fec1fd8e.jpg)

I hope everything is in its place.

**Comment by risbansal** [comment] 2018-03-07 12:32
A few changes. Can you please make the title as Rust Hacks at Cummins. And actually in first look it seems like AR and VR is hands-on but Rust is not. So a little change to highlight Rust as hands-on. Maybe you could flip the sentences for both.

**Comment by pransh15** [comment] 2018-03-07 12:35
The title of the issue is Rust at Cummins hence, the title. Anyway, I'll change that!
Well, this is a statement which has been used for Hands-On workshops with Rust previously, "Get your hands dirty with Rust!". @rowdymehul, what do you think?

**Comment by pransh15** [comment] 2018-03-07 12:43
![rustatcummins](https://user-images.githubusercontent.com/18158596/37092735-ed9928f8-2232-11e8-9d43-4ba5211bcb6a.jpg)

Updated the title.

**Comment by risbansal** [comment] 2018-03-07 12:45
Cool. How about having the title in the same colour. I think that would look good. Or we could have it in two lines if it is in different colours.

**Comment by nomadicmehul** [comment] 2018-03-07 12:46
True @pransh15 even I have used that statement and it sounds good instead.

**Comment by nomadicmehul** [comment] 2018-03-07 12:51
@risbansal I think current title looks good, different makes more appealing. @pransh15 do we have any other color combinations for the background ?

**Comment by pransh15** [comment] 2018-03-07 19:57
![rustatcummins](https://user-images.githubusercontent.com/18158596/37114978-e16768dc-226f-11e8-948e-6407fa0beff4.jpg)

A brighter background in the same color scheme.

**Comment by risbansal** [comment] 2018-03-08 11:20
Great! Thanks @pransh15.

**Comment by pransh15** [comment] 2018-03-18 13:30
Awesome. I hope the event went well. Closing this! :)

**Closed as completed by pransh15** 2018-03-18 13:30 UTC
Labels: Help Wanted, Graphic Design Needed
